### ISSUE TITLE
"Gangversteck einnehmen" produziert massive Fehlermeldungen

### ISSUE THREAD

**Issue by Umbarion** [Umbarion/Project_Warlord#12]
![20161118201227_1](https://cloud.githubusercontent.com/assets/23502732/20443067/8f953666-adcb-11e6-8c39-e945e10a0ec2.jpg)
![20161118201236_1](https://cloud.githubusercontent.com/assets/23502732/20443068/8f96e39e-adcb-11e6-8d6e-d1f192b52dc3.jpg)

**Comment by Paini** [comment]
fixed
