### ISSUE TITLE
Fehlerhafte Anzeige bei Abbau von Rohstoffen

### ISSUE THREAD

**Issue by Umbarion** [Umbarion/Project_Warlord#17]
Es gibt keine Spezifizierung, was abgebaut wurde. Lediglich "(s)".

![20161120141350_1](https://cloud.githubusercontent.com/assets/23502732/20463076/dcd7a092-af2b-11e6-8f55-2e3c51513ba0.jpg)

**Comment by Paini** [comment]
fixed
