### ISSUE TITLE
Nutzobjekte und Rohstoffobjekte Config erstellen

### ISSUE THREAD

**Issue by Paini** [Umbarion/Project_Warlord#4]

**Comment by Umbarion** [comment]
class PWA_Item
    {
        units[] = {};
        weapons[]=
        {
            "PWA_tool",
            "PWA_pickaxe",
            "PWA_shovel",
            "PWA_secateurs",
            "PWA_prospectingtools",
            "PWA_drillingequipment"
        };
        requiredVersion = 0.1;
        requiredAddons[] = 
            {
                "A3_Characters_F_BLUFOR"
            };
        magazines[]=
        {
            "PWA_Item",
            "PWA_package_medium",
            //Standard-Items A3 Life Mod 
            "PWA_coffee",
            "PWA_waterbottle",
            "PWA_energydrink",
            "PWA_beefjerky",
            "PWA_donut",
            "PWA_toolkit",
            "PWA_jerrycan_empty",
            "PWA_jerrycan_full",
            "PWA_lockpick",
            "PWA_boltcutter",
            "PWA_nailribbon",
            "PWA_storagecrate_small",
            "PWA_storagecrate_big",
            "PWA_storagecrate_huge",
            "PWA_defibrillator",
            //Rohstoffe und Materialien
            // Fische
            "PWA_catshark_raw",
            "PWA_mackerel_raw",
            "PWA_mullet_raw",
            "PWA_ornate_raw",
            "PWA_salema_raw",
            "PWA_tuna_raw",
            "PWA_bluecrab_raw",
            "PWA_snowcrab_raw",
            "PWA_kingcrab_raw",
            "PWA_lobster_raw",
            //Agrar
            "PWA_date_raw",
            "PWA_nuts_raw",
            "PWA_millet_raw",
            "PWA_millet_processed",
            "PWA_cigarettes_raw",
            "PWA_cigarettes_processed",
            //Bodenschätze
            "PWA_stone_raw",
            "PWA_stone_processed",
            "PWA_copper_raw",
            "PWA_copper_processed",
            "PWA_iron_raw",
            "PWA_iron_processed",
            "PWA_gold_raw",
            "PWA_gold_processed",
            "PWA_platinum_raw",
            "PWA_platinum_processed",
            "PWA_coke_raw",
            "PWA_coke_processed",
            "PWA_oil_raw",
            "PWA_oil_processed",
            "PWA_oil_postprocessed",
            "PWA_diamond_raw",
            "PWA_diamond_processed",
            "PWA_ruby_raw",
            "PWA_ruby_processed",
            //Drogen
            "PWA_cannabis_raw",
            "PWA_cannabis_processed",
            "PWA_cocaine_raw",
            "PWA_cocaine_processed",
            "PWA_heroin_raw",
            "PWA_heroin_processed",
            "PWA_gunpowder_processed",
            "PWA_brownbrown_processed",
        };
    };
